apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: ceph-osd-01
  uid: 3E0468D694B849D5
spec:
  ssh: true
  image:
    ociClaim:
      ref: weaveworks/ignite-centos
  cpus: 2
  diskSize: 3GB
  memory: 1GB
status:
  state: Running
---
apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: ceph-osd-02
  uid: 64E9C4DED494440A
spec:
  ssh: true
  image:
    ociClaim:
      ref: weaveworks/ignite-centos
  cpus: 2
  diskSize: 3GB
  memory: 1GB
status:
  state: Running
---
apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: ceph-osd-03
  uid: 6758A9E69F944DB6
spec:
  ssh: true
  image:
    ociClaim:
      ref: weaveworks/ignite-centos
  cpus: 2
  diskSize: 3GB
  memory: 1GB
status:
  state: Running
