#!/bin/sh
set -ex

# Ignite

export IGN_VERSION=v0.4.2

inst_ignite() {
    curl -fLo ignite https://github.com/weaveworks/ignite/releases/download/${IGN_VERSION}/ignite
    chmod +x ignite
    mv ignite /usr/local/bin
}

. /etc/os-release
case $ID in
ubuntu)
    apt-get update && apt-get install -y --no-install-recommends \
	    jq \
	    docker-ce \
	    dmsetup \
	    openssh-client \
	    git \
	    binutils \
	    python-wheel \
	    python-setuptools \
	    python-pip \
	    python-netaddr
    break
    ;;
centos)
    yum install epel-release -y
    yum install -y docker e2fsprogs openssh-clients git jq python-pip
    break
    ;;
*)
    echo "Distro $ID Not support"
    exit 1
    ;;
esac


if ! command -v ignite; then
    inst_ignite
else
    if [ "$IGN_VERSION" != "$(ignite version --output json | jq '.igniteVersion.gitVersion' | tr -d '\"')" ]; then
        echo "Versions differ"
        inst_ignite
    fi
fi

pip install -r requirements.txt
