#!/bin/sh
set -ex

hashi_inst() {
    # Gist that installs hashicorp tools
    curl -fsSL https://git.io/fjMMS | sudo sh -s -- $1 $2 $3
}

# Hashi everything
hashi_inst terraform 0.12.5 zip
hashi_inst vagrant 2.2.5 deb
hashi_inst packer 1.4.2 zip

# Python
apt-get update -y
apt-get install -y \
	    python-wheel \
	    python-setuptools \
	    python-pip \
	    python-netaddr

# Pip stuff
pip install -r requirements.txt

