#!/bin/sh
set -e

# Ansible ceph
ceph_ansi_dir="$(dirname "$0")/../ceph-ansible"

git clone https://github.com/ceph/ceph-ansible.git "$ceph_ansi_dir" || true
cd "$ceph_ansi_dir"
git checkout stable-4.0

mv vagrant_variables.yml.sample vagrant_variables.yml || true

vagrant up
