#!/bin/sh
set -e

cd "$(dirname "$0")/.."

git clone https://github.com/ceph/ceph-ansible.git /tmp/ceph-ansible || true

# Dis gus ting
IPS="$(sudo ignite ps | awk '{print $12}' | grep -v NAME)"
# echo $IPS | tr ' ' '\n' | xargs -I {} ssh-keygen -f "/root/.ssh/known_hosts" -R {}
# echo $IPS | tr ' ' '\n' | xargs -I {} ssh-copy-id root@{}

ansible-playbook -i instances/hosts.ini /tmp/ceph-ansible/site.yml.sample
