apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: ceph-osd-01
  uid: 3E0468D694B849D5
spec:
  ssh: true
  image:
    ociClaim:
      ref: tyhal/fried-squid
  cpus: 1
  diskSize: 10GB
  memory: 1GB
status:
  state: Running
